# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0coauthservice\"\x07\n\x05\x45mpty\"y\n\x0c\x41uthResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x19\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\rrefresh_token\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x0f\n\r_access_tokenB\x10\n\x0e_refresh_token\"\"\n\x11IntrospectRequest\x12\r\n\x05token\x18\x01 \x01(\t\"$\n\x12IntrospectResponse\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\" \n\x0fUserInfoRequest\x12\r\n\x05token\x18\x01 \x01(\t\" \n\x10UserInfoResponse\x12\x0c\n\x04info\x18\x01 \x01(\t\"\x1e\n\rRevokeRequest\x12\r\n\x05token\x18\x01 \x01(\t2\xb1\x02\n\x0cOAuthService\x12\x43\n\x0c\x41uthenticate\x12\x13.oauthservice.Empty\x1a\x1a.oauthservice.AuthResponse\"\x00\x30\x01\x12Q\n\nIntrospect\x12\x1f.oauthservice.IntrospectRequest\x1a .oauthservice.IntrospectResponse\"\x00\x12K\n\x08UserInfo\x12\x1d.oauthservice.UserInfoRequest\x1a\x1e.oauthservice.UserInfoResponse\"\x00\x12<\n\x06Revoke\x12\x1b.oauthservice.RevokeRequest\x1a\x13.oauthservice.Empty\"\x00\x42\t\n\x07serviceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\007service'
  _EMPTY._serialized_start=31
  _EMPTY._serialized_end=38
  _AUTHRESPONSE._serialized_start=40
  _AUTHRESPONSE._serialized_end=161
  _INTROSPECTREQUEST._serialized_start=163
  _INTROSPECTREQUEST._serialized_end=197
  _INTROSPECTRESPONSE._serialized_start=199
  _INTROSPECTRESPONSE._serialized_end=235
  _USERINFOREQUEST._serialized_start=237
  _USERINFOREQUEST._serialized_end=269
  _USERINFORESPONSE._serialized_start=271
  _USERINFORESPONSE._serialized_end=303
  _REVOKEREQUEST._serialized_start=305
  _REVOKEREQUEST._serialized_end=335
  _OAUTHSERVICE._serialized_start=338
  _OAUTHSERVICE._serialized_end=643
# @@protoc_insertion_point(module_scope)
